### ISSUE TITLE
Cannot start CO-Manager with local database

### ISSUE THREAD

**Issue by j-fuentes** [CloudOpting/cloudopting-manager#99]
I am trying to install all the platform locally on my machine (https://github.com/CloudOpting/deploy-cloudopting).

I have a database populated with the [sql script](https://github.com/CloudOpting/deploy-cloudopting/blob/master/database/files/prod_postgres_backup_cloudopting_2015.12.10_v2.backup.sql) @xeviscc dumped from the DB.

I've modified the `rest-component/src/main/resources/config/application-prod.yml` to generate the war (see [build instruction for manager](https://github.com/CloudOpting/deploy-cloudopting/blob/master/manager/build-instructions.md)) like this:

```yaml
...
datasource:
    dataSourceClassName: org.postgresql.ds.PGSimpleDataSource
    driver: org.postgresql.Driver
    url: jdbc:postgresql://db:5432/cloudopting
    databaseName: cloudopting
    serverName: db
    username: postgres
    password: 1qaz2wsx
...
```

I launch the [docker-compose.yml](https://github.com/CloudOpting/deploy-cloudopting/blob/master/docker-compose.yml), but the manager raises several exception I cannot understand.

I tried with the default `application-prod.yml` and it worked.

Manually, I can connect to the local database and it seems all the data is there in the proper place.

What am I missing? Is there another information on the database needed to run the project? I just have the `cloudopting` table.
